'use strict';
// Input supplies the energy. Recoil spends it; unattended ropes never lose health.
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),$=s=>document.querySelector(s);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),mix=(a,b,t)=>a+(b-a)*t,TAU=Math.PI*2;
const palette=['#edb4ca','#f2d790','#b8dfe9','#eed4bc','#b8dba9'];
const sprite=new Image(),tints=[];sprite.src='assets/sea-friend-sprites.webp?v=1';
sprite.onload=()=>palette.forEach(color=>{const c=document.createElement('canvas');c.width=sprite.width;c.height=sprite.height;const x=c.getContext('2d');x.drawImage(sprite,0,0);x.globalCompositeOperation='source-atop';x.globalAlpha=.22;x.fillStyle=color;x.fillRect(0,0,c.width,c.height);tints.push(c);});

let W=390,H=780,mode='title',chars=[],links=[],particles=[],words=[],pointer=null;
let elapsed=0,clock=0,last=0,lastInput=-10,caught=0,shake=0,flash=0,combo=0,comboTime=0,stats={},endWin=false;
let soundOn=true,musicMode=1,audio=null,beat=0,nextBeat=0,hidden=false;
const oldBgm=new Audio('assets/maou-orchestra24.mp3?v=1');oldBgm.loop=true;oldBgm.volume=.22;
function resize(){const ow=W,oh=H;W=innerWidth;H=innerHeight;const d=Math.min(devicePixelRatio||1,2);canvas.width=W*d;canvas.height=H*d;ctx.setTransform(d,0,0,d,0,0);if(chars.length)chars.forEach(c=>{c.x*=W/ow;c.y*=H/oh;c.home*=W/ow;c.anchor*=W/ow;c.homeY*=H/oh;c.r=Math.min(28,W*.066);});pointer=null;}
addEventListener('resize',resize);resize();

// A small original marimba / bubble score, with a separate volume envelope per note.
function unlockAudio(){if(!audio){const A=window.AudioContext||window.webkitAudioContext;if(A)audio=new A();}if(audio?.state==='suspended')audio.resume().catch(()=>{});}
function tone(f,t=.12,vol=.06,type='sine',delay=0,end=f){if(!soundOn||!audio||hidden||audio.state!=='running')return;const now=audio.currentTime+delay,o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(f,now);o.frequency.exponentialRampToValueAtTime(Math.max(30,end),now+t);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(vol,now+.009);g.gain.exponentialRampToValueAtTime(.0001,now+t);o.connect(g);g.connect(audio.destination);o.start(now);o.stop(now+t+.025);}
const seFiles={tap:'boyon',stretch:'boyon',tangle:'boyon',bonk:'boyon',recoil:'boyon',snap:'boyon',swim:'boyon',caught:'boyon',win:'boyon',lose:'boyon'};
const sePool={},seLast={};
function se(kind,c,strength=.4){if(!soundOn||hidden)return;const file=seFiles[kind];if(!file)return;const now=performance.now();if(now-(seLast[file]||-1000)<(kind==='stretch'?180:90))return;seLast[file]=now;if(!sePool[file])sePool[file]=Array.from({length:3},()=>new Audio('assets/lab/'+file+'.mp3'));const pool=sePool[file],a=pool.find(a=>a.paused)||pool[0];a.pause();a.currentTime=0;a.volume=clamp(.18+strength*.55,.15,.8);a.playbackRate=kind==='stretch'?.85:1;a.play().catch(()=>{});}
function music(){}
function syncMusic(){oldBgm.pause();if(soundOn&&mode==='play'&&!hidden)oldBgm.play().catch(()=>{});}

function setup(){const heights=[.42,.55,.46,.59,.40],space=Math.min(82,W*.175);chars=palette.map((color,id)=>{const home=W/2+(id-2)*space,hp=[128,150,162,150,128][id];return {id,color,home,anchor:home,homeY:H*heights[id],x:home,y:H*heights[id],vx:0,vy:0,r:Math.min(28,W*.066),hp,maxHp:hp,charge:0,hold:0,twist:0,reach:.12,yaw:id*.4,spin:0,tilt:0,stretch:0,pop:0,recoil:0,cool:0,active:0,lastDir:id%2?1:-1,free:false,escape:0,trail:0,solo:false};});links=[];for(let a=0;a<5;a++)for(let b=a+1;b<5;b++)links.push({a,b,power:0,cool:0,bodyCool:0,tA:.6,tB:.6,x:0,y:0,phase:0,turns:1.4,span:.17,spinDir:1});particles=[];words=[];pointer=null;elapsed=0;caught=0;combo=0;comboTime=0;shake=flash=0;stats={taps:0,drags:0,flicks:0,recoils:0,tangles:0,bonks:0};}
function start(){unlockAudio();setup();mode='play';$('#start-panel').classList.add('hidden');$('#result-panel').classList.add('hidden');$('#hud').classList.remove('hidden');oldBgm.currentTime=0;nextBeat=audio?.currentTime||0;beat=0;syncMusic();label('つつく！ のばす！ はなす！',W/2,H*.76,'#ffecaa',2);}
function label(){}
function burst(x,y,n=8,color='#c6ffed'){for(let i=0;i<n;i++){const a=Math.random()*TAU,v=30+Math.random()*130;particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v-30,r:2+Math.random()*4,life:.5+Math.random()*.7,color});}if(particles.length>180)particles.splice(0,particles.length-180);}
function remaining(){return chars.filter(c=>!c.free);}
function damage(c,n){if(c.free||mode!=='play')return;const mult=remaining().length===1?2.2:remaining().length===2?1.25:1;c.hp-=n*mult;if(c.hp<=0)release(c);}
function energize(c,power,dir,kind){if(c.free)return;lastInput=clock;const edge=c.id===0||c.id===4?1.15:1,tap=kind==='tap';c.active=1.5;if(tap){c.lastDir=dir||c.lastDir;c.hold=3;}c.charge=clamp(c.charge+power*edge*(tap?1:.16),0,100);c.spin=clamp(c.spin+(dir||c.lastDir)*(tap?13:kind==='flick'?4:1.2),-29,29);c.pop=.24;damage(c,power*(tap?.16:.012)*edge);if(!c.free&&c.charge>=100&&c.cool<=0)recoil(c);}
function recoil(c){c.charge=100;c.hold=3;c.cool=3;c.recoil=.25;c.spin*=.22;c.pop=.24;stats.recoils++;shake=2;se('recoil',c,.75);burst(c.x,c.y-c.r,8);}
function release(c){if(c.free)return;c.free=true;c.hp=0;c.escape=0;c.vy=-120;c.vx=(c.id<2?-1:1)*80;stats.rescued=(stats.rescued||0)+1;shake=7;flash=.14;burst(c.x,c.y-c.r,24,'#fff2a6');label('ぷちんっ！',c.x,c.y-45,'#fff2a6',1.1);se('snap',c,.9);se('swim',c,.5);remaining().forEach(o=>{o.hp=Math.max(1,o.hp-3);});const left=remaining();if(left.length===1){left[0].hp=Math.min(left[0].hp,38);left[0].solo=true;label('あとひとり！ つついて決めよう',W/2,H*.77,'#fff2a6',2);}if(navigator.vibrate)navigator.vibrate(25);}
function pick(x,y){let best=null,dist=62;chars.forEach(c=>{const d=Math.hypot(c.x-x,c.y-y);if(!c.free&&d<dist){dist=d;best=c;}});return best;}
canvas.addEventListener('pointerdown',e=>{if(mode!=='play'||pointer)return;unlockAudio();const c=pick(e.clientX,e.clientY);if(!c)return;pointer={id:e.pointerId,c,sx:e.clientX,sy:e.clientY,x:e.clientX,y:e.clientY,lx:e.clientX,ly:e.clientY,moved:0,bank:0,time:clock,mx:0,my:0,mt:clock,offsetX:c.x-e.clientX,offsetY:c.y-e.clientY};canvas.setPointerCapture(e.pointerId);c.pop=.3;});
canvas.addEventListener('pointermove',e=>{const p=pointer;if(!p||e.pointerId!==p.id)return;const x=clamp(e.clientX,10,W-10),y=clamp(e.clientY,H*.18,H*.8),dx=x-p.x,dy=y-p.y,dt=Math.max(.016,clock-p.mt);p.mx=clamp(dx/dt,-1100,1100);p.my=clamp(dy/dt,-1100,1100);p.mt=clock;p.x=x;p.y=y;p.moved+=Math.hypot(dx,dy);p.bank+=Math.hypot(dx,dy);if(p.moved>12&&!p.c.free){p.c.active=1.5;if(p.bank>16){const energy=Math.min(12,p.bank*.17);p.bank=0;energize(p.c,energy,Math.sign(dx)||p.c.lastDir,'drag');stats.drags++;if(Math.random()<.3)burst(p.c.x,p.c.y,2);if(clock-(p.soundAt||0)>.16){se('stretch',p.c);p.soundAt=clock;}}}});
function pointerEnd(e,cancel=false){const p=pointer;if(!p||p.id!==e.pointerId)return;pointer=null;if(canvas.hasPointerCapture?.(e.pointerId))canvas.releasePointerCapture(e.pointerId);if(cancel||p.c.free||mode!=='play')return;const c=p.c;if(p.moved<14&&Math.hypot(e.clientX-p.sx,e.clientY-p.sy)<18){stats.taps++;c.vy-=90;c.vx+=c.lastDir*32;energize(c,24,c.lastDir,'tap');se('tap',c);burst(c.x,c.y+c.r,5);label(c.solo?'ラスト！ ぐるぐる！':'くるるっ',c.x,c.y-48,c.color,.6);}else{stats.flicks++;const dx=p.x-p.sx,dy=p.y-p.sy,len=Math.hypot(dx,dy),fresh=clock-p.mt<.15;const edge=c.id===0||c.id===4?1.25:1;c.vx=clamp((fresh?p.mx*.38:0)+(c.home-c.x)*2,-540,540)*edge;c.vy=clamp((fresh?p.my*.38:0)+(c.homeY-c.y)*2,-520,520);energize(c,clamp(len*.13,10,32),Math.sign(dx)||c.lastDir,'flick');c.stretch=.35;burst(c.x,c.y,9);se('tap',c);label(len>W*.25?'びよーーん！':'びゅんっ！',c.x,c.y-48);}}
canvas.addEventListener('pointerup',e=>pointerEnd(e));canvas.addEventListener('pointercancel',e=>pointerEnd(e,true));canvas.addEventListener('lostpointercapture',e=>{if(pointer?.id===e.pointerId)pointer=null;});

function ropePath(c){const pts=[],length=c.y-c.r*.55+12;for(let i=0;i<=64;i++){const t=i/64;let x=mix(c.anchor,c.x,t)+Math.sin(Math.PI*t)*(Math.sin(clock*1.7+t*7+c.id)*5-c.vx*.035),y=-12+length*t,z=0;links.forEach(k=>{if(k.power<.02||(k.a!==c.id&&k.b!==c.id)||chars[k.a].free||chars[k.b].free)return;const kt=k.a===c.id?k.tA:k.tB,side=(k.a===c.id?1:-1)*k.spinDir,s=(t-kt)/k.span;if(Math.abs(s)>=1)return;const soft=Math.sin((1-Math.abs(s))*Math.PI/2)**2,envelope=soft*k.power,angle=k.phase+s*TAU*k.turns,axisX=k.x+s*(chars[k.b].x-chars[k.a].x)*.08,axisY=k.y+s*Math.min(105,H*.14),radius=(13+k.power*7)*envelope;x=mix(x,axisX,envelope*.88)+side*Math.cos(angle)*radius;y=mix(y,axisY,envelope*.78)+Math.sin(angle)*radius*.42;z+=side*Math.sin(angle)*envelope;});pts.push({x,y,z,t});}return pts;}
function interact(dt){const paths=chars.map(c=>c.free?null:ropePath(c));links.forEach(k=>{k.cool=Math.max(0,k.cool-dt);k.bodyCool=Math.max(0,k.bodyCool-dt);k.power=Math.max(0,k.power-dt*.22);k.phase+=dt*(3+k.power*5)*k.spinDir;const a=chars[k.a],b=chars[k.b];if(a.free||b.free)return;const relative=Math.hypot(a.vx-b.vx,a.vy-b.vy);if((a.active>0||b.active>0)&&relative>35&&k.cool===0){let best=23,hit=null;for(let i=10;i<65;i+=3)for(let j=10;j<65;j+=3){const p=paths[k.a][i],q=paths[k.b][j],d=Math.hypot(p.x-q.x,p.y-q.y);if(d<best){best=d;hit={p,q};}}if(hit){k.tA=clamp(hit.p.t,.34,.76);k.tB=clamp(hit.q.t,.34,.76);const pa=paths[k.a][Math.round(k.tA*64)],pb=paths[k.b][Math.round(k.tB*64)];k.x=(pa.x+pb.x)/2;k.y=(pa.y+pb.y)/2;k.power=1;k.cool=.9;stats.tangles++;combo=comboTime>0?combo+1:1;comboTime=2.1;const stored=clamp((Math.abs(a.twist)+Math.abs(b.twist))/ (100/12),0,2),dir=a.x>b.x?1:-1;k.spinDir=dir;k.turns=clamp(1.15+stored*.45+relative/900,1.15,2.15);k.span=clamp(.17+stored*.025,.17,.21);a.vx+=dir*(72+stored*35);b.vx-=dir*(72+stored*35);a.vy-=55;b.vy+=40;a.spin=dir*20;b.spin=-dir*20;a.charge=clamp(a.charge*.82+12,0,100);b.charge=clamp(b.charge*.82+12,0,100);a.active=b.active=1;damage(a,1.8*(1+stored*2.5));damage(b,1.8*(1+stored*2.5));burst(k.x,k.y,Math.round(5+stored*9),'#d9fff4');label(stored>1?'こすれて効いた！':combo>1?`こすれ ${combo}連鎖！`:'キュッ！',k.x,k.y-18,'#e0fff4');se('tangle',a,stored/2);shake=1+stored*2;}}
if(k.power>.15){const dx=b.x-a.x,dy=b.y-a.y,tug=dt*k.power*1.35,orbit=dt*k.power*.55*k.spinDir;a.vx+=dx*tug-dy*orbit;b.vx-=dx*tug+dy*orbit;a.vy+=dy*tug*.35+dx*orbit;b.vy-=dy*tug*.35+dx*orbit;const rub=relative*k.power*dt*.004;if(rub>.01){damage(a,rub);damage(b,rub);}}
// Body contact only gives a soft bounce. Damage is attached to the ribbons.
const dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),gap=a.r+b.r;if(d<gap&&d>1){const push=(gap-d)*dt*13,nx=dx/d,ny=dy/d;a.vx-=nx*push;b.vx+=nx*push;a.vy-=ny*push;b.vy+=ny*push;if(relative>45&&k.bodyCool<=0){k.bodyCool=.48;stats.bonks++;a.vx-=nx*70;b.vx+=nx*70;a.vy-=45;b.vy-=35;a.pop=b.pop=.42;a.spin-=ny*8;b.spin+=ny*8;burst((a.x+b.x)/2,(a.y+b.y)/2,10,'#fff2ca');label('ぽよん！',(a.x+b.x)/2,(a.y+b.y)/2-30,'#fff1b0',.65);se('bonk',a);shake=2;}}});}
function beginCaught(){if(mode!=='play')return;mode='caught';caught=0;pointer=null;oldBgm.pause();se('caught');shake=5;label('みつかった……！',W*.58,H*.42,'#ffe6cb',1.2);}
function update(dt){clock+=dt;shake*=Math.exp(-dt*12);flash=Math.max(0,flash-dt);comboTime-=dt;particles.forEach(p=>{p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.exp(-dt*2);p.vy-=45*dt;});particles=particles.filter(p=>p.life>0);words.forEach(w=>{w.life-=dt;w.y-=dt*17;});words=words.filter(w=>w.life>0);
if(mode==='title'){chars.forEach(c=>{c.y=c.homeY+Math.sin(clock*1.4+c.id)*9;c.yaw+=dt*.5;});return;}
chars.forEach(c=>{if(c.free){c.escape+=dt;c.vx+=(c.id<2?-1:1)*dt*45;c.vy-=dt*70;c.x+=c.vx*dt;c.y+=c.vy*dt;c.yaw+=dt*7;c.trail-=dt;if(c.trail<0){burst(c.x,c.y+c.r,2);c.trail=.13;}return;}if(mode!=='play')return;c.active=Math.max(0,c.active-dt);c.cool=Math.max(0,c.cool-dt);c.recoil=Math.max(0,c.recoil-dt);c.pop*=Math.exp(-dt*9);c.stretch*=Math.exp(-dt*7);const held=pointer?.c===c&&pointer.moved>12;
if(held){const tx=clamp(pointer.x+pointer.offsetX,c.r,W-c.r),ty=clamp(pointer.y+pointer.offsetY,H*.2,H*.8);c.vx=(tx-c.x)*15;c.vy=(ty-c.y)*15;}else{c.vx+=((c.home-c.x)*3.4)*dt;c.vy+=((c.homeY-c.y)*6.5)*dt;c.vx*=Math.exp(-dt*1.4);c.vy*=Math.exp(-dt*1.8);}c.x=clamp(c.x+c.vx*dt,c.r,W-c.r);c.y=clamp(c.y+c.vy*dt,H*.2,H*.8);const beforeCharge=c.charge;c.hold=Math.max(0,(c.hold||0)-dt);if(c.hold===0&&c.active<=0)c.charge=Math.max(0,c.charge-dt*6);c.spin*=Math.exp(-dt*(c.charge>=99?9:2.6));c.yaw+=c.spin*dt+c.lastDir*(c.charge-beforeCharge)*.035;c.twist=mix(c.twist,c.lastDir*(c.charge/12),1-Math.exp(-dt*3));c.reach=mix(c.reach,.18+.82*c.charge/100,1-Math.exp(-dt*3));c.tilt=mix(c.tilt,clamp(c.vx*.002,-.7,.7),1-Math.exp(-dt*8));if(c.charge>=100&&c.cool<=0)recoil(c);});
if(mode==='play'){if(clock-lastInput<1.6)interact(dt);else links.forEach(k=>{k.power=Math.max(0,k.power-dt*.6);k.cool=Math.max(0,k.cool-dt);k.bodyCool=Math.max(0,k.bodyCool-dt);});elapsed+=dt;if(!remaining().length)finish(true);else if(elapsed>=60)beginCaught();music();}else if(mode==='caught'){caught+=dt;const tx=W*.60,ty=H*.36;remaining().forEach((c,i)=>{const pull=dt*(.35+caught*1.7);c.x+=((tx+(i-2)*5)-c.x)*pull;c.y+=(ty-c.y)*pull;c.yaw+=dt*(5+caught*8);c.pop=.18+Math.sin(clock*18)*.08;});shake=Math.max(shake,caught*4);if(caught>1.6)finish(false);}}

function ribbon(c,minT=0,maxT=1,detail=false){
  const path=ropePath(c),dense=[];
  // Subdivide drawing independently of the coarse contact mesh: no ladder-like seams.
  for(let i=0;i<path.length-1;i++)for(let j=0;j<4;j++){const p=path[i],q=path[i+1],u=j/4;dense.push({x:mix(p.x,q.x,u),y:mix(p.y,q.y,u),t:mix(p.t,q.t,u)});}dense.push(path[path.length-1]);
  const pts=dense.filter(p=>p.t>=minT&&p.t<=maxT);if(pts.length<2)return;
  const base=Math.min(17,W*.04),stretch=clamp(c.homeY/c.y,.75,1.15);
  const phase=t=>c.twist*TAU*(1-(1-clamp(t/Math.max(.15,c.reach),0,1))**2)+t*2+c.yaw*.12;
  const width=p=>base*(.13+.87*Math.abs(Math.cos(phase(p.t))))*stretch;
  for(let i=0;i<pts.length-1;i++){const p=pts[i],q=pts[i+1],w=width(p),v=width(q);ctx.beginPath();ctx.moveTo(p.x-w,p.y);ctx.lineTo(q.x-v,q.y);ctx.lineTo(q.x+v,q.y);ctx.lineTo(p.x+w,p.y);ctx.closePath();ctx.fillStyle=Math.cos((phase(p.t)+phase(q.t))/2)>0?'#61a64e':'#285e45';ctx.fill();}
  for(const side of [-1,1]){ctx.beginPath();pts.forEach((p,i)=>{const x=p.x+side*width(p);i?ctx.lineTo(x,p.y):ctx.moveTo(x,p.y);});ctx.strokeStyle=detail?'#173f35':'#295c40';ctx.lineWidth=detail?1.7:1.2;ctx.stroke();}
  ctx.beginPath();pts.forEach((p,i)=>{const off=Math.cos(phase(p.t))*base*.85*stretch;i?ctx.lineTo(p.x+off,p.y):ctx.moveTo(p.x+off,p.y);});ctx.strokeStyle='#b4d577';ctx.lineWidth=2;ctx.stroke();
  if(c.charge>60){ctx.globalAlpha=(c.charge-60)/80;ctx.strokeStyle='#e8ffc0';ctx.lineWidth=3;ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.globalAlpha=1;}
}
function frictionEffects(){links.forEach(k=>{if(k.power<.16||chars[k.a].free||chars[k.b].free)return;ctx.save();ctx.translate(k.x,k.y);ctx.rotate(k.phase*.08);ctx.globalAlpha=k.power*.7;ctx.strokeStyle='#e4fff5';ctx.lineWidth=2.2;for(const side of [-1,1]){ctx.beginPath();ctx.arc(0,0,18+side*5,-1.05,.3);ctx.stroke();ctx.beginPath();ctx.arc(0,0,18+side*5,2.1,3.45);ctx.stroke();}ctx.globalAlpha=k.power*.35;ctx.beginPath();ctx.ellipse(0,0,31,12,0,0,TAU);ctx.stroke();ctx.restore();});}
function character(c){const cos=Math.cos(c.yaw),view=cos>.42?0:cos<-.42?2:1,size=c.r*3.05,squash=c.pop+Math.min(.22,Math.abs(c.vy)*.00035);ctx.save();ctx.translate(c.x,c.y);ctx.rotate(c.tilt+Math.sin(c.yaw)*Math.min(.25,Math.abs(c.spin)*.009));ctx.scale((.86+.14*Math.abs(cos))*(1+squash*.4),1-squash*.25);if(Math.sin(c.yaw)<0)ctx.scale(-1,1);if(sprite.complete&&sprite.naturalWidth){const sw=sprite.width/3;ctx.drawImage(tints[c.id]||sprite,view*sw,0,sw,sprite.height,-size/2,-size/2,size,size);}else{ctx.fillStyle=c.color;ctx.beginPath();ctx.ellipse(0,0,c.r,c.r*.92,0,0,TAU);ctx.fill();ctx.fillStyle='#233c44';if(cos>0){for(const x of [-8,8]){ctx.beginPath();ctx.arc(x,-2,2.4,0,TAU);ctx.fill();}ctx.beginPath();ctx.arc(0,4,4,0,Math.PI);ctx.stroke();}}ctx.restore();if(Math.abs(c.spin)>9){ctx.strokeStyle=c.recoil>0?'#ffed9f':'#c8fff1';ctx.lineWidth=2;ctx.globalAlpha=.6;for(let i=0;i<2;i++){ctx.beginPath();ctx.ellipse(c.x,c.y,c.r*1.6,c.r*.52,-.2,clock*13+i*Math.PI,clock*13+i*Math.PI+1.9);ctx.stroke();}ctx.globalAlpha=1;}
if(mode==='play'&&!c.free){ctx.fillStyle='#092e4c99';ctx.fillRect(c.x-19,c.y+c.r+17,38,4);ctx.fillStyle=c.hp<25?'#ffe5a1':'#b8e6cf';ctx.fillRect(c.x-19,c.y+c.r+17,38*c.hp/c.maxHp,4);if(c.charge>10){ctx.beginPath();ctx.strokeStyle=c.charge>75?'#ffe5a1':'#c6ffea88';ctx.lineWidth=2;ctx.arc(c.x,c.y,c.r*1.5,-Math.PI/2,-Math.PI/2+TAU*c.charge/100);ctx.stroke();}}}
function sea(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#248a99');g.addColorStop(.48,'#12657b');g.addColorStop(1,'#10364e');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.save();ctx.globalAlpha=.07;ctx.fillStyle='#cbfff0';for(let i=0;i<5;i++){const x=W*(i*.24-.1)+Math.sin(clock*.2+i)*18;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x+30,0);ctx.lineTo(x+180,H);ctx.lineTo(x+50,H);ctx.fill();}ctx.restore();for(let i=0;i<32;i++){const x=((i*97.3)%W)+Math.sin(clock*.5+i)*12,y=H-((clock*(9+i%4*5)+i*57)% (H+30)),r=2+i%5;ctx.strokeStyle='#c3fff138';ctx.lineWidth=1;ctx.beginPath();ctx.arc(x,y,r,0,TAU);ctx.stroke();ctx.fillStyle='#ffffff44';ctx.beginPath();ctx.arc(x-r*.3,y-r*.3,Math.max(.8,r*.18),0,TAU);ctx.fill();}ctx.fillStyle='#163e50';ctx.beginPath();ctx.moveTo(0,H);for(let x=0;x<=W+20;x+=20)ctx.lineTo(x,H-27-Math.sin(x*.018)*9);ctx.lineTo(W,H);ctx.fill();}
function mermaid(front=false){
 const engulfed=mode==='caught'||(mode==='result'&&!endWin);
 if((mode!=='play'&&!engulfed)||elapsed<6||front!==engulfed)return;
 const p=clamp((elapsed-6)/54,0,1),lunge=engulfed?clamp(caught/1.2,0,1):0;
 const x=mix(W*.76,W*.5,p),y=mix(H*.17,H*.35,p),radius=mix(14,Math.min(W*.43,H*.33),p*p);
 const r=mix(radius,Math.hypot(W,H)*.85,lunge*lunge);
 ctx.save();ctx.translate(x,y);ctx.globalAlpha=.15+.85*p;ctx.fillStyle='#020e16';
 ctx.beginPath();ctx.moveTo(-r*.20,r*.65);ctx.quadraticCurveTo(-r*.38,r*1.03,0,r*1.08);ctx.lineTo(r*.37,r*1.17);ctx.lineTo(r*.26,r*.92);ctx.lineTo(r*.48,r*.82);ctx.quadraticCurveTo(r*.20,r*.88,r*.18,r*.65);ctx.fill();
 ctx.beginPath();ctx.ellipse(0,0,r,r*.83,0,0,TAU);ctx.fill();
 ctx.fillStyle='#ffffbb';ctx.shadowColor='#ffff9b';ctx.shadowBlur=12+20*p;
 for(const side of [-1,1]){ctx.beginPath();ctx.ellipse(side*r*.32,-r*.08,r*.08,r*.13,side*.18,0,TAU);ctx.fill();}
 ctx.shadowBlur=0;if(p>.8){ctx.fillStyle='#000';ctx.beginPath();ctx.ellipse(0,r*.33,r*.34,r*(.06+lunge*.20),0,0,TAU);ctx.fill();}ctx.restore();
}

function draw(){sea();mermaid();ctx.save();ctx.translate(Math.sin(clock*67)*shake,Math.cos(clock*83)*shake);chars.filter(c=>!c.free).forEach(c=>ribbon(c));frictionEffects();chars.forEach(character);particles.forEach(p=>{ctx.globalAlpha=clamp(p.life,0,1);ctx.strokeStyle=p.color;ctx.lineWidth=1.6;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,TAU);ctx.stroke();});ctx.globalAlpha=1;words.forEach(w=>{ctx.globalAlpha=clamp(w.life*3,0,1);ctx.textAlign='center';ctx.font='900 17px system-ui';ctx.lineWidth=4;ctx.strokeStyle='#164957';const x=clamp(w.x,85,W-85);ctx.strokeText(w.text,x,w.y);ctx.fillStyle=w.color;ctx.fillText(w.text,x,w.y);});ctx.restore();ctx.globalAlpha=1;mermaid(true);if(flash>0){ctx.fillStyle=`rgba(226,255,210,${flash})`;ctx.fillRect(0,0,W,H);}if(mode==='play'||mode==='caught'){const left=remaining().length;$('#score').textContent=`${5-left} / 5`;$('#distance').textContent=Math.max(0,Math.ceil(60-elapsed));$('#combo').textContent=comboTime>0&&combo>1?`${combo} 連鎖！`:left===1?'ラスト！':'';$('#timer-fill').style.transform=`scaleX(${Math.max(0,1-elapsed/60)})`;$('#play-hint').textContent=mode==='caught'?'みつかった……！':left===1?'最後の子をタップ！ ぎゅるんと脱出':elapsed<8?'タップでねじる · 引っぱって絡める！':'ためて → 絡めて → こすって効かせる！';}}
function finish(win){if(mode!=='play'&&mode!=='caught')return;const bitten=mode==='caught';mode='result';endWin=win;pointer=null;oldBgm.pause();if(win)se('win');else if(!bitten)se('lose');$('#result-panel').classList.remove('hidden');$('#hud').classList.add('hidden');$('#result-panel .eyebrow').textContent=win?'ぷちんっ、すいすい。全員脱出！':`${5-remaining().length}人、逃げられた！`;
$('#result-score').textContent=win?elapsed.toFixed(1):'あと少し';$('#result-unit').textContent=win?'秒で、自由！':'';$('#result-copy').textContent=win?(elapsed<30?'ねじりの達人！ 海の向こうまで、すいすい。':'みんな無事！ いっぱい暴れて、いっぱいねじれた。'):'つつくだけでも大丈夫。ためて、ギュルルン！';$('#result-stats').textContent=`くるるん ${stats.recoils}回　·　からまり ${stats.tangles}回`;
try{const key='wakame-best-v3',best=Number(localStorage.getItem(key))||Infinity;if(win&&elapsed<best)localStorage.setItem(key,String(elapsed));const value=Math.min(win?elapsed:Infinity,best);$('#best-score').textContent=Number.isFinite(value)?`この端末のベスト ${value.toFixed(1)}秒`:'';}catch{$('#best-score').textContent='';}}
$('#start-button').onclick=start;$('#retry-button').onclick=start;$('#sound-button').onclick=()=>{unlockAudio();soundOn=!soundOn;$('#sound-button').textContent=soundOn?'🔊':'🔇';$('#sound-button').setAttribute('aria-label',soundOn?'音を消す':'音を出す');if(!soundOn)Object.values(sePool).flat().forEach(a=>a.pause());syncMusic();};$('#share-button').onclick=async()=>{const text=endWin?`コンブゲーム！ ${elapsed.toFixed(1)}秒で5人を救出。`:'コンブゲーム！ つついて、のばして、ぎゅルルン！';const url=location.href.split('?')[0];try{if(navigator.share)await navigator.share({title:'コンブゲーム',text,url});else{await navigator.clipboard.writeText(text+' '+url);$('#share-button').textContent='リンクをコピーしたよ';}}catch{}};
document.addEventListener('visibilitychange',()=>{hidden=document.hidden;pointer=null;last=performance.now();if(hidden){oldBgm.pause();audio?.suspend();}else{if(soundOn)audio?.resume().catch(()=>{});syncMusic();}});
setup();function loop(now){const dt=Math.min(.033,Math.max(0,(now-last)/1000));last=now;if(!hidden){update(dt);draw();}requestAnimationFrame(loop);}requestAnimationFrame(loop);
